name: Pull Request Flow

# triggers
on:
  pull_request:
    types: [edited, synchronize, reopened, opened]
    branches:
      - main
      
concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  pr-check:
    name: Pull Request Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.4'
          channel: 'stable'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter
          
      - name: Setup SSH Keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          
      - name: Cache Fastlane dependencies
        uses: actions/cache@v2
        env:
          fastlane-cache-key: fastlane-cache
          fastlane-path: ~/.gem
        with:
          path: ${{ env.fastlane-path }}
          key: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}
            
      - name: Install Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
          
      - name: Run Lint and Tests
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec fastlane flutter pull_request
